### ISSUE TITLE
no attribute resolver defined

### ISSUE THREAD

**Issue by zwayne** [python-odin/baldr#3]
Seeing this issue with baldr 0.4.5 when running from a Django command. I have baldr listed INSTALLED_APPS in settings.py, but it doesn't seem to load the field resolver. The normal odin resource resolvers load, but not baldr. 

Trying to run tests from command line using python manage.py <command>. 

```
File "/Users/wyoung/git/zBackend/devices/malware/resources.py", line 399, in <module>
    class GlobalScanResponseToSample(odin.Mapping):
  File "/Users/wyoung/.virtualenvs/zBackend/lib/python2.7/site-packages/odin/mapping/__init__.py", line 192, in __new__
    raise MappingSetupError('`to_obj` %r does not have an attribute resolver defined.' % to_obj)
odin.exceptions.MappingSetupError: `to_obj` <class 'devices.malware.models.Sample'> does not have an attribute resolver defined.
```

**Comment by timsavage** [comment]
Which version of Django are you using? 

There have been subtle changes in the way django loads the models.py file, in later releases. The approached used in the current development version of baldr is to force the models file to be loaded which will ensure that the Model attribute resolver is registered.

A workaround if you don't want to try using the current development version (it has had a large amount of additional work done on it over the 0.4.5 release although there may be some breaking changes) would be to simply add `import baldr.models` somewhere in your test code.

**Comment by zwayne** [comment]
Thanks for the quick reply. We are on an old version... 1.6. Maintaining this code and hoping to retire it very soon.

**Comment by timsavage** [comment]
In that case using importing baldr.models should solve your issue.

**Comment by zwayne** [comment]
Still getting same error. I will keep digging.

**Comment by zwayne** [comment]
Oh, I moved it up above the other imports and got further. I think that might have solved it. 

Thanks!

**Comment by timsavage** [comment]
No problem, I was just going to suggest that. The Mapping defintions are evaluated/created when the containing module is first imported.
